jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3

      - name: Show Dockerfile contents
        run: |
          echo "PWD: $(pwd)"
          ls -la
          echo "--- Dockerfile ---"
          cat Dockerfile

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker Image
        run: docker build -t nikhilcodes22/react-app:latest .

      - name: Publish image to Docker Hub
        run: docker push nikhilcodes22/react-app:latest
